### ISSUE TITLE
[feature request] A better way to translate 

### ISSUE THREAD

**Issue by jontaix** [jackBonadies/SeekerAndroid#21]
It's a good idea to set up a translation cloud-based service such as Crowdin or Webslate.
Translating using a spreadsheet is not an easy way to do this. What do you think?

**Comment by jackBonadies** [comment]
Thanks for the suggestion.  I really want Seeker in other languages, and its one of the most requested features.  I contacted Crowdin since they have a form you can fill out for open source projects to use the service for free, but otherwise I will go with Webslate.  

The spreadsheet did not get too much engagement.  Though I am not sure what is to be expected.  Whatever makes it easiest for volunteers to translate, I am all for.  

I will update you when the status changes.

**Comment by jackBonadies** [comment]
Okay it seems like the Crowdin request got approved immediately.. so I will work on setting it up.

**Comment by jontaix** [comment]
Thanks

**Comment by jackBonadies** [comment]
https://crowdin.com/project/seeker

Here is the link.  Please help out if you can.  And if you note any issues let me know or reopen this issue.  The platform seems promising.

**Comment by jackBonadies** [comment]
Also, feel free to give any suggestions.  There are options for pre-translation using Machine Translation.  And the option for additional machine translation engines in the suggestions.  Right now, nothing is pre-translated, and when translating a string suggestions from machine translation and existing translations appear below it.

**Comment by jontaix** [comment]
> Also, feel free to give any suggestions. There are options for pre-translation using Machine Translation. And the option for additional machine translation engines in the suggestions. Right now, nothing is pre-translated, and when translating a string suggestions from machine translation and existing translations appear below it.

Please add Brazilian Portuguese. I can't add a new locale in crowndin

**Comment by jackBonadies** [comment]
Added
